version: '3.5'

services:
  database:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./data:/data/postgresql
    restart: always
volumes:
  data:
    driver: local