"""vincular operacao com carteira

Revision ID: 1f686649c7f9
Revises: ece70956b3bc
Create Date: 2023-04-06 20:32:13.698523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f686649c7f9'
down_revision = 'ece70956b3bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
