"""Incluindo o cascade

Revision ID: 7ccce4aafdc7
Revises: e8fd33090bd4
Create Date: 2023-04-07 11:40:26.988341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ccce4aafdc7'
down_revision = 'e8fd33090bd4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
