"""atualizando tabela ativos_carteira

Revision ID: daf6a8511c75
Revises: 
Create Date: 2023-04-30 14:17:06.891743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daf6a8511c75'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ativos_carteira',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('codigo_ativo', sa.String(), nullable=True),
    sa.Column('preco_medio', sa.Float(), nullable=True),
    sa.Column('quantidade_ativos', sa.Integer(), nullable=True),
    sa.Column('preco_atual', sa.Float(), nullable=True),
    sa.Column('status_em_carteira', sa.BOOLEAN(), nullable=True),
    sa.Column('carteira_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['carteira_id'], ['carteira.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ativos_carteira_id'), 'ativos_carteira', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ativos_carteira_id'), table_name='ativos_carteira')
    op.drop_table('ativos_carteira')
    # ### end Alembic commands ###
