"""Incluindo o cascade

Revision ID: e8fd33090bd4
Revises: 80e03079ab82
Create Date: 2023-04-07 11:37:21.247164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8fd33090bd4'
down_revision = '80e03079ab82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
