"""migração inicial

Revision ID: ece70956b3bc
Revises: 
Create Date: 2023-04-06 19:18:17.308888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ece70956b3bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('carteira',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patrimonio', sa.Float(), nullable=True),
    sa.Column('total_investido', sa.Float(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carteira_id'), 'carteira', ['id'], unique=False)
    op.create_table('ativos_carteira',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('codigo_ativo', sa.String(), nullable=True),
    sa.Column('preco_medio', sa.Float(), nullable=True),
    sa.Column('quantidade_ativo', sa.Integer(), nullable=True),
    sa.Column('status_em_carteira', sa.Integer(), nullable=True),
    sa.Column('preco_atual', sa.Float(), nullable=True),
    sa.Column('carteira_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['carteira_id'], ['carteira.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ativos_carteira_id'), 'ativos_carteira', ['id'], unique=False)
    op.create_table('operacao',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('codigo_ativo', sa.String(), nullable=True),
    sa.Column('tipo_operacao', sa.String(), nullable=True),
    sa.Column('valor_operacao', sa.Float(), nullable=True),
    sa.Column('quantidade_ativo', sa.Integer(), nullable=True),
    sa.Column('data_operacao', sa.DateTime(), nullable=True),
    sa.Column('ativos_carteira_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ativos_carteira_id'], ['ativos_carteira.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operacao_id'), 'operacao', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operacao_id'), table_name='operacao')
    op.drop_table('operacao')
    op.drop_index(op.f('ix_ativos_carteira_id'), table_name='ativos_carteira')
    op.drop_table('ativos_carteira')
    op.drop_index(op.f('ix_carteira_id'), table_name='carteira')
    op.drop_table('carteira')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
